// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeeHelper
{
    internal sealed partial class Vsix
    {
        public const string Id = "DeeReferenceHelper.55d96ae0-09ad-4bb3-966b-a227f765a6fe";
        public const string Name = "DeeReferenceHelper";
        public const string Description = @"CriticalManufaturing Dee Reference helper";
        public const string Language = "en-US";
        public const string Version = "8.5";
        public const string Author = "Tim Lin";
        public const string Tags = "";
    }
}
