// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeeHelper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DeeHelperString = "87c960f5-4cb6-4b85-ba33-c7c0b44ea1fd";
        public static Guid DeeHelper = new Guid(DeeHelperString);

        public const string guidDeeHelperPackageCmdSetString = "7a69a15e-8d77-4824-bceb-9bb90766f316";
        public static Guid guidDeeHelperPackageCmdSet = new Guid(guidDeeHelperPackageCmdSetString);

        public const string guidImages1String = "e0e72a92-3f77-4423-b7dd-5846c0b7d25c";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int cmdidGetActionGroupWindowCommand = 0x0100;
        public const int cmdidGetActionGroupWindowCommand1 = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}