// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeeHelper
{
    internal sealed partial class Vsix
    {
        public const string Id = "DeeHelper_v17.0819639b-43ac-460e-837d-14bdd19ccfba";
        public const string Name = "DeeHelper";
        public const string Description = @"CriticalManufaturing Dee Reference helper";
        public const string Language = "en-US";
        public const string Version = "9.4";
        public const string Author = "Tim Lin";
        public const string Tags = "";
    }
}
